namespace: default
ignoreChildren: true
regoQuery: "data[_].main"
policies:
  - example/policies
objects:
  - group: apps
    version: v1
    resource: deployments
  - group: apps
    version: v1
    resource: daemonsets
  - group: apps
    version: v1
    resource: replicasets
  - group: kafka.strimzi.io
    version: v1beta2
    resource: kafkaconnects